import Zeta5.Certificate.InnerBranches.Group08

/-! Generated by `scripts/generate_inner_branches.py`. Each theorem
checks its complete domain using proof-producing arithmetic. -/

namespace Zeta5.Certificate

theorem inner_branch_90 (x : ℝ) (hl : (27 / 2) < x) (hr : x < (500 / 37)) :
    innerR x = (-182 + (719 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (31 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (176) + ((14 + -1 * x) - (-1 + (3 / 40) * x)) * (125) +
        (1 / 2 - (14 + -1 * x)) * (100) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (14 + -1 * x)
      (176) (125) (100) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (27 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (13 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (24 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_91 (x : ℝ) (hl : (500 / 37) < x) (hr : x < (320 / 23)) :
    innerR x = (-207 + (793 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (31 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (176) + ((14 + -1 * x) - (-1 + (3 / 40) * x)) * (125) +
        (1 / 2 - (14 + -1 * x)) * (100) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (14 + -1 * x)
      (176) (125) (100) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (27 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (13 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (25 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_92 (x : ℝ) (hl : (320 / 23) < x) (hr : x < (600 / 43)) :
    innerR x = (-191 + (747 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (32 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (207) + ((14 + -1 * x) - (-1 + (3 / 40) * x)) * (156) +
        (1 / 2 - (14 + -1 * x)) * (130) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (14 + -1 * x)
      (207) (156) (130) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (27 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (13 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (25 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_93 (x : ℝ) (hl : (600 / 43) < x) (hr : x < 14) :
    innerR x = (-146 + (309 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (32 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (14 + -1 * x) * (207) + ((-1 + (3 / 40) * x) - (14 + -1 * x)) * (184) +
        (1 / 2 - (-1 + (3 / 40) * x)) * (130) := by
    apply integral_three_strips (innerGammaIntegrand x) (14 + -1 * x) (-1 + (3 / 40) * x)
      (207) (184) (130) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (27 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (13 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (25 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_94 (x : ℝ) (hl : 14 < x) (hr : x < (520 / 37)) :
    innerR x = (-160 + (73 / 5) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (32 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-14 + 1 * x) * (161) + ((-1 + (3 / 40) * x) - (-14 + 1 * x)) * (184) +
        (1 / 2 - (-1 + (3 / 40) * x)) * (130) := by
    apply integral_three_strips (innerGammaIntegrand x) (-14 + 1 * x) (-1 + (3 / 40) * x)
      (161) (184) (130) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (28 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (14 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (25 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_95 (x : ℝ) (hl : (520 / 37) < x) (hr : x < (330 / 23)) :
    innerR x = (-225 + (769 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (32 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (161) + ((-14 + 1 * x) - (-1 + (3 / 40) * x)) * (104) +
        (1 / 2 - (-14 + 1 * x)) * (130) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (-14 + 1 * x)
      (161) (104) (130) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (28 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (14 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (26 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_96 (x : ℝ) (hl : (330 / 23) < x) (hr : x < (620 / 43)) :
    innerR x = ((-417 / 2) + (723 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (192) + ((-14 + 1 * x) - (-1 + (3 / 40) * x)) * (135) +
        (1 / 2 - (-14 + 1 * x)) * (162) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (-14 + 1 * x)
      (192) (135) (162) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (28 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (14 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (26 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_97 (x : ℝ) (hl : (620 / 43) < x) (hr : x < (29 / 2)) :
    innerR x = ((-417 / 2) + (723 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (192) + ((-14 + 1 * x) - (-1 + (3 / 40) * x)) * (135) +
        (1 / 2 - (-14 + 1 * x)) * (162) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (-14 + 1 * x)
      (192) (135) (162) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (13 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (28 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (14 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (26 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_98 (x : ℝ) (hl : (29 / 2) < x) (hr : x < (540 / 37)) :
    innerR x = (-223 + (763 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (192) + ((15 + -1 * x) - (-1 + (3 / 40) * x)) * (135) +
        (1 / 2 - (15 + -1 * x)) * (108) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (15 + -1 * x)
      (192) (135) (108) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (15 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (29 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (14 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (26 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_99 (x : ℝ) (hl : (540 / 37) < x) (hr : x < (340 / 23)) :
    innerR x = (-250 + (837 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (192) + ((15 + -1 * x) - (-1 + (3 / 40) * x)) * (135) +
        (1 / 2 - (15 + -1 * x)) * (108) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (15 + -1 * x)
      (192) (135) (108) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (14 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (15 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (29 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (14 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (27 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

end Zeta5.Certificate
