import Zeta5.Certificate.InnerBranches.Group04

/-! Generated by `scripts/generate_inner_branches.py`. Each theorem
checks its complete domain using proof-producing arithmetic. -/

namespace Zeta5.Certificate

theorem inner_branch_50 (x : ℝ) (hl : (200 / 23) < x) (hr : x < (380 / 43)) :
    innerR x = (-88 + (159 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (20 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (9 + -1 * x) * (17) + ((1 + (-3 / 40) * x) - (9 + -1 * x)) * (0) +
        (1 / 2 - (1 + (-3 / 40) * x)) * (42) := by
    apply integral_three_strips (innerGammaIntegrand x) (9 + -1 * x) (1 + (-3 / 40) * x)
      (17) (0) (42) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (17 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (8 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_51 (x : ℝ) (hl : (380 / 43) < x) (hr : x < 9) :
    innerR x = (-88 + (159 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (20 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (9 + -1 * x) * (17) + ((1 + (-3 / 40) * x) - (9 + -1 * x)) * (0) +
        (1 / 2 - (1 + (-3 / 40) * x)) * (42) := by
    apply integral_three_strips (innerGammaIntegrand x) (9 + -1 * x) (1 + (-3 / 40) * x)
      (17) (0) (42) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (17 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (8 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_52 (x : ℝ) (hl : 9 < x) (hr : x < (210 / 23)) :
    innerR x = (-97 + (71 / 10) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (20 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-9 + 1 * x) * (-17) + ((1 + (-3 / 40) * x) - (-9 + 1 * x)) * (0) +
        (1 / 2 - (1 + (-3 / 40) * x)) * (42) := by
    apply integral_three_strips (innerGammaIntegrand x) (-9 + 1 * x) (1 + (-3 / 40) * x)
      (-17) (0) (42) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (18 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (9 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_53 (x : ℝ) (hl : (210 / 23) < x) (hr : x < (340 / 37)) :
    innerR x = ((-173 / 2) + (119 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (21 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-9 + 1 * x) * (0) + ((1 + (-3 / 40) * x) - (-9 + 1 * x)) * (18) +
        (1 / 2 - (1 + (-3 / 40) * x)) * (60) := by
    apply integral_three_strips (innerGammaIntegrand x) (-9 + 1 * x) (1 + (-3 / 40) * x)
      (0) (18) (60) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (18 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (9 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_54 (x : ℝ) (hl : (340 / 37) < x) (hr : x < (400 / 43)) :
    innerR x = ((-207 / 2) + (39 / 5) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (21 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-9 + 1 * x) * (0) + ((1 + (-3 / 40) * x) - (-9 + 1 * x)) * (18) +
        (1 / 2 - (1 + (-3 / 40) * x)) * (60) := by
    apply integral_three_strips (innerGammaIntegrand x) (-9 + 1 * x) (1 + (-3 / 40) * x)
      (0) (18) (60) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (18 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (9 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (17 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_55 (x : ℝ) (hl : (400 / 43) < x) (hr : x < (19 / 2)) :
    innerR x = ((-147 / 2) + (183 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (21 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (1 + (-3 / 40) * x) * (0) + ((-9 + 1 * x) - (1 + (-3 / 40) * x)) * (45) +
        (1 / 2 - (-9 + 1 * x)) * (60) := by
    apply integral_three_strips (innerGammaIntegrand x) (1 + (-3 / 40) * x) (-9 + 1 * x)
      (0) (45) (60) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (8 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (18 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (9 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (17 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_56 (x : ℝ) (hl : (19 / 2) < x) (hr : x < (220 / 23)) :
    innerR x = (-83 + (223 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (21 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (1 + (-3 / 40) * x) * (0) + ((10 + -1 * x) - (1 + (-3 / 40) * x)) * (45) +
        (1 / 2 - (10 + -1 * x)) * (30) := by
    apply integral_three_strips (innerGammaIntegrand x) (1 + (-3 / 40) * x) (10 + -1 * x)
      (0) (45) (30) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (10 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (19 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (9 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (17 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_57 (x : ℝ) (hl : (220 / 23) < x) (hr : x < (360 / 37)) :
    innerR x = (-72 + (177 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (22 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (1 + (-3 / 40) * x) * (19) + ((10 + -1 * x) - (1 + (-3 / 40) * x)) * (64) +
        (1 / 2 - (10 + -1 * x)) * (48) := by
    apply integral_three_strips (innerGammaIntegrand x) (1 + (-3 / 40) * x) (10 + -1 * x)
      (19) (64) (48) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (10 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (19 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (9 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (17 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_58 (x : ℝ) (hl : (360 / 37) < x) (hr : x < (420 / 43)) :
    innerR x = (-117 + (181 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (22 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (10 + -1 * x) * (19) + ((1 + (-3 / 40) * x) - (10 + -1 * x)) * (0) +
        (1 / 2 - (1 + (-3 / 40) * x)) * (48) := by
    apply integral_three_strips (innerGammaIntegrand x) (10 + -1 * x) (1 + (-3 / 40) * x)
      (19) (0) (48) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (10 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (10 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (19 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (9 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (18 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_59 (x : ℝ) (hl : (420 / 43) < x) (hr : x < 10) :
    innerR x = (-117 + (181 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (22 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (10 + -1 * x) * (19) + ((1 + (-3 / 40) * x) - (10 + -1 * x)) * (0) +
        (1 / 2 - (1 + (-3 / 40) * x)) * (48) := by
    apply integral_three_strips (innerGammaIntegrand x) (10 + -1 * x) (1 + (-3 / 40) * x)
      (19) (0) (48) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (10 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (9 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (10 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (19 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (9 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (18 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

end Zeta5.Certificate
