import Zeta5.Certificate.InnerDefinitions

/-! Generated by `scripts/generate_inner_branches.py`. Each theorem
checks its complete domain using proof-producing arithmetic. -/

namespace Zeta5.Certificate

theorem inner_branch_0 (x : ℝ) (hl : 3 < x) (hr : x < (70 / 23)) :
    innerR x = (-6 + (18 / 5) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-3 + 1 * x) * (-9) + ((0 + (3 / 40) * x) - (-3 + 1 * x)) * (-6) +
        (1 / 2 - (0 + (3 / 40) * x)) * (-30) := by
    apply integral_three_strips (innerGammaIntegrand x) (-3 + 1 * x) (0 + (3 / 40) * x)
      (-9) (-6) (-30) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (2 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (2 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (5 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_1 (x : ℝ) (hl : (70 / 23) < x) (hr : x < (120 / 37)) :
    innerR x = ((-5 / 2) + (49 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-3 + 1 * x) * (-8) + ((0 + (3 / 40) * x) - (-3 + 1 * x)) * (-4) +
        (1 / 2 - (0 + (3 / 40) * x)) * (-28) := by
    apply integral_three_strips (innerGammaIntegrand x) (-3 + 1 * x) (0 + (3 / 40) * x)
      (-8) (-4) (-28) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (2 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (2 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (5 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_2 (x : ℝ) (hl : (120 / 37) < x) (hr : x < (140 / 43)) :
    innerR x = ((-35 / 2) + (283 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (0 + (3 / 40) * x) * (-8) + ((-3 + 1 * x) - (0 + (3 / 40) * x)) * (-35) +
        (1 / 2 - (-3 + 1 * x)) * (-28) := by
    apply integral_three_strips (innerGammaIntegrand x) (0 + (3 / 40) * x) (-3 + 1 * x)
      (-8) (-35) (-28) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (2 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_3 (x : ℝ) (hl : (140 / 43) < x) (hr : x < (10 / 3)) :
    innerR x = ((-35 / 2) + (283 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (0 + (3 / 40) * x) * (-8) + ((-3 + 1 * x) - (0 + (3 / 40) * x)) * (-35) +
        (1 / 2 - (-3 + 1 * x)) * (-28) := by
    apply integral_three_strips (innerGammaIntegrand x) (0 + (3 / 40) * x) (-3 + 1 * x)
      (-8) (-35) (-28) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (2 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_4 (x : ℝ) (hl : (10 / 3) < x) (hr : x < (80 / 23)) :
    innerR x = (-17 + (277 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (0 + (3 / 40) * x) * (-8) + ((-3 + 1 * x) - (0 + (3 / 40) * x)) * (-35) +
        (1 / 2 - (-3 + 1 * x)) * (-28) := by
    apply integral_three_strips (innerGammaIntegrand x) (0 + (3 / 40) * x) (-3 + 1 * x)
      (-8) (-35) (-28) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (2 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_5 (x : ℝ) (hl : (80 / 23) < x) (hr : x < (7 / 2)) :
    innerR x = (-13 + (231 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (8 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (0 + (3 / 40) * x) * (-5) + ((-3 + 1 * x) - (0 + (3 / 40) * x)) * (-32) +
        (1 / 2 - (-3 + 1 * x)) * (-24) := by
    apply integral_three_strips (innerGammaIntegrand x) (0 + (3 / 40) * x) (-3 + 1 * x)
      (-5) (-32) (-24) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (2 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_6 (x : ℝ) (hl : (7 / 2) < x) (hr : x < (160 / 43)) :
    innerR x = ((-33 / 2) + (271 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (8 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (0 + (3 / 40) * x) * (-5) + ((4 + -1 * x) - (0 + (3 / 40) * x)) * (-32) +
        (1 / 2 - (4 + -1 * x)) * (-40) := by
    apply integral_three_strips (innerGammaIntegrand x) (0 + (3 / 40) * x) (4 + -1 * x)
      (-5) (-32) (-40) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (4 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_7 (x : ℝ) (hl : (160 / 43) < x) (hr : x < (140 / 37)) :
    innerR x = ((-9 / 2) + (71 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (8 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (4 + -1 * x) * (-5) + ((0 + (3 / 40) * x) - (4 + -1 * x)) * (-10) +
        (1 / 2 - (0 + (3 / 40) * x)) * (-40) := by
    apply integral_three_strips (innerGammaIntegrand x) (4 + -1 * x) (0 + (3 / 40) * x)
      (-5) (-10) (-40) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (4 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (4 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (6 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_8 (x : ℝ) (hl : (140 / 37) < x) (hr : x < (90 / 23)) :
    innerR x = ((-23 / 2) + (27 / 5) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (8 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (4 + -1 * x) * (-5) + ((0 + (3 / 40) * x) - (4 + -1 * x)) * (-10) +
        (1 / 2 - (0 + (3 / 40) * x)) * (-40) := by
    apply integral_three_strips (innerGammaIntegrand x) (4 + -1 * x) (0 + (3 / 40) * x)
      (-5) (-10) (-40) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (4 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (4 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_9 (x : ℝ) (hl : (90 / 23) < x) (hr : x < 4) :
    innerR x = (-7 + (17 / 4) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (9 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (4 + -1 * x) * (0) + ((0 + (3 / 40) * x) - (4 + -1 * x)) * (-6) +
        (1 / 2 - (0 + (3 / 40) * x)) * (-36) := by
    apply integral_three_strips (innerGammaIntegrand x) (4 + -1 * x) (0 + (3 / 40) * x)
      (0) (-6) (-36) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (4 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (3 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (4 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (-1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (3 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (0 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (7 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

end Zeta5.Certificate
