import Zeta5.Certificate.InnerDefinitions

/-! Generated by `scripts/generate_inner_branches.py`. Each theorem
checks its complete domain using proof-producing arithmetic. -/

namespace Zeta5.Certificate

theorem inner_branch_140 (x : ℝ) (hl : (39 / 2) < x) (hr : x < (840 / 43)) :
    innerR x = ((-927 / 2) + (931 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (44 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (315) + ((20 + -1 * x) - (-1 + (3 / 40) * x)) * (228) +
        (1 / 2 - (20 + -1 * x)) * (190) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (20 + -1 * x)
      (315) (228) (190) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (20 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (39 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (19 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (36 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_141 (x : ℝ) (hl : (840 / 43) < x) (hr : x < (450 / 23)) :
    innerR x = ((-801 / 2) + (401 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (44 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (20 + -1 * x) * (315) + ((-1 + (3 / 40) * x) - (20 + -1 * x)) * (280) +
        (1 / 2 - (-1 + (3 / 40) * x)) * (190) := by
    apply integral_three_strips (innerGammaIntegrand x) (20 + -1 * x) (-1 + (3 / 40) * x)
      (315) (280) (190) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (20 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (20 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (39 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (19 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (36 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_142 (x : ℝ) (hl : (450 / 23) < x) (hr : x < 20) :
    innerR x = (-378 + (189 / 10) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (45 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (20 + -1 * x) * (360) + ((-1 + (3 / 40) * x) - (20 + -1 * x)) * (324) +
        (1 / 2 - (-1 + (3 / 40) * x)) * (234) := by
    apply integral_three_strips (innerGammaIntegrand x) (20 + -1 * x) (-1 + (3 / 40) * x)
      (360) (324) (234) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (20 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (19 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (20 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (39 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (19 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (36 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

end Zeta5.Certificate
