import Zeta5.Certificate.InnerBranches.Group10

/-! Generated by `scripts/generate_inner_branches.py`. Each theorem
checks its complete domain using proof-producing arithmetic. -/

namespace Zeta5.Certificate

theorem inner_branch_110 (x : ℝ) (hl : 16 < x) (hr : x < (370 / 23)) :
    innerR x = (-244 + (84 / 5) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (36 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-16 + 1 * x) * (189) + ((-1 + (3 / 40) * x) - (-16 + 1 * x)) * (216) +
        (1 / 2 - (-1 + (3 / 40) * x)) * (150) := by
    apply integral_three_strips (innerGammaIntegrand x) (-16 + 1 * x) (-1 + (3 / 40) * x)
      (189) (216) (150) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (15 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (15 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (32 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (29 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_111 (x : ℝ) (hl : (370 / 23) < x) (hr : x < (600 / 37)) :
    innerR x = ((-451 / 2) + (313 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (37 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-16 + 1 * x) * (224) + ((-1 + (3 / 40) * x) - (-16 + 1 * x)) * (252) +
        (1 / 2 - (-1 + (3 / 40) * x)) * (186) := by
    apply integral_three_strips (innerGammaIntegrand x) (-16 + 1 * x) (-1 + (3 / 40) * x)
      (224) (252) (186) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (15 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (15 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (32 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (29 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_112 (x : ℝ) (hl : (600 / 37) < x) (hr : x < (700 / 43)) :
    innerR x = ((-601 / 2) + (811 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (37 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (224) + ((-16 + 1 * x) - (-1 + (3 / 40) * x)) * (155) +
        (1 / 2 - (-16 + 1 * x)) * (186) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (-16 + 1 * x)
      (224) (155) (186) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (15 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (32 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (30 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_113 (x : ℝ) (hl : (700 / 43) < x) (hr : x < (33 / 2)) :
    innerR x = ((-601 / 2) + (811 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (37 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (224) + ((-16 + 1 * x) - (-1 + (3 / 40) * x)) * (155) +
        (1 / 2 - (-16 + 1 * x)) * (186) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (-16 + 1 * x)
      (224) (155) (186) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (15 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (32 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (30 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_114 (x : ℝ) (hl : (33 / 2) < x) (hr : x < (380 / 23)) :
    innerR x = (-317 + (851 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (37 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (224) + ((17 + -1 * x) - (-1 + (3 / 40) * x)) * (155) +
        (1 / 2 - (17 + -1 * x)) * (124) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (17 + -1 * x)
      (224) (155) (124) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (17 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (30 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_115 (x : ℝ) (hl : (380 / 23) < x) (hr : x < (50 / 3)) :
    innerR x = (-298 + (161 / 8) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (38 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (261) + ((17 + -1 * x) - (-1 + (3 / 40) * x)) * (192) +
        (1 / 2 - (17 + -1 * x)) * (160) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (17 + -1 * x)
      (261) (192) (160) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (17 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (30 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_116 (x : ℝ) (hl : (50 / 3) < x) (hr : x < (720 / 43)) :
    innerR x = ((-591 / 2) + (799 / 40) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (38 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (-1 + (3 / 40) * x) * (261) + ((17 + -1 * x) - (-1 + (3 / 40) * x)) * (192) +
        (1 / 2 - (17 + -1 * x)) * (160) := by
    apply integral_three_strips (innerGammaIntegrand x) (-1 + (3 / 40) * x) (17 + -1 * x)
      (261) (192) (160) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (17 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (30 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_117 (x : ℝ) (hl : (720 / 43) < x) (hr : x < (620 / 37)) :
    innerR x = ((-483 / 2) + (67 / 4) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (38 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (17 + -1 * x) * (261) + ((-1 + (3 / 40) * x) - (17 + -1 * x)) * (232) +
        (1 / 2 - (-1 + (3 / 40) * x)) * (160) := by
    apply integral_three_strips (innerGammaIntegrand x) (17 + -1 * x) (-1 + (3 / 40) * x)
      (261) (232) (160) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (17 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (17 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (30 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_118 (x : ℝ) (hl : (620 / 37) < x) (hr : x < (390 / 23)) :
    innerR x = ((-545 / 2) + (93 / 5) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (38 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (17 + -1 * x) * (261) + ((-1 + (3 / 40) * x) - (17 + -1 * x)) * (232) +
        (1 / 2 - (-1 + (3 / 40) * x)) * (160) := by
    apply integral_three_strips (innerGammaIntegrand x) (17 + -1 * x) (-1 + (3 / 40) * x)
      (261) (232) (160) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (17 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (17 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (31 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

theorem inner_branch_119 (x : ℝ) (hl : (390 / 23) < x) (hr : x < 17) :
    innerR x = (-253 + (349 / 20) * x) := by
  have ht : ⌊2 * (23 / 20) * x⌋ = (39 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =
      (17 + -1 * x) * (300) + ((-1 + (3 / 40) * x) - (17 + -1 * x)) * (270) +
        (1 / 2 - (-1 + (3 / 40) * x)) * (198) := by
    apply integral_three_strips (innerGammaIntegrand x) (17 + -1 * x) (-1 + (3 / 40) * x)
      (300) (270) (198) (by linarith) (by linarith) (by linarith)
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (17 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
    · intro z hz
      rcases hz with ⟨hzl, hzr⟩
      have h0 : ⌊x - z⌋ = (16 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h1 : ⌊x + z⌋ = (17 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h2 : ⌊(3 / 40) * x - z⌋ = (0 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      have h3 : ⌊(3 / 40) * x + z⌋ = (1 : ℤ) := by
        apply Int.floor_eq_iff.mpr
        constructor <;> norm_num <;> linarith
      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]
      norm_num
  have hq : ⌊2 * x⌋ = (33 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hx : ⌊x⌋ = (16 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have ha : ⌊(3 / 40) * x⌋ = (1 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  have hm : ⌊2 * ((37 / 40) * x)⌋ = (31 : ℤ) := by
    apply Int.floor_eq_iff.mpr
    constructor <;> norm_num <;> linarith
  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,
    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]
  norm_num
  simp only [max_def]
  split <;> linarith

end Zeta5.Certificate
