#!/usr/bin/env python3
"""Generate proof scripts, not trusted answers, for the source inner branches.

Rational midpoints select candidate strips and floor values. Every candidate
is checked on its entire open domain by the generated Lean proofs. The
original Gamma integral is evaluated by three-strip integral congruence.
"""
from pathlib import Path
from fractions import Fraction as F
import sys
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'certificates'))
from verify import Poly, X, alpha, lam, H, pieces_R


def rat(x):
    x = F(x)
    return str(x.numerator) if x.denominator == 1 else f'({x.numerator} / {x.denominator})'


def affine(p):
    return f'({rat(p.c[0])} + {rat(p.c[1] if len(p.c) > 1 else 0)} * x)'


def floorproof(name, expr, val, indent='  '):
    return (f'{indent}have {name} : ⌊{expr}⌋ = ({val} : ℤ) := by\n'
            f'{indent}  apply Int.floor_eq_iff.mpr\n'
            f'{indent}  constructor <;> norm_num <;> linarith\n')


points = {F(3), F(20)}
for c in {F(2), 2*alpha, 2*lam, 2*H, 4*alpha, 2*(1-alpha), 2*(1+alpha)}:
    for k in range(int(3*c), int(20*c)+2):
        t = F(k)/c
        if 3 < t < 20:
            points.add(t)
points = sorted(points)
assert len(points) == 144
out = ROOT / 'Zeta5' / 'Certificate' / 'InnerBranches'
out.mkdir(exist_ok=True)
rows = []
for i, (l, r) in enumerate(zip(points, points[1:])):
    mid = (l+r)/2
    f = X - int(mid//1)
    g = alpha*X - int((alpha*mid)//1)
    df = f if f(mid) <= F(1,2) else 1-f
    dg = g if g(mid) <= F(1,2) else 1-g
    a, b = sorted([df,dg], key=lambda p: p(mid))
    strips = [Poly(0), a, b, Poly(F(1,2))]
    T = int((2*H*mid)//1)
    values = []
    floors = []
    for za,zb in zip(strips,strips[1:]):
        z = (za(mid)+zb(mid))/2
        v = [int(t//1) for t in [mid-z,mid+z,alpha*mid-z,alpha*mid+z]]
        ell = v[0]+v[1]+1
        B = 3*(v[2]+v[3]+1)
        values.append((T-B)*(T+B-ell-5))
        floors.append(v)
    P = pieces_R(l,r)
    rows.append((l,r,P.c[0],P.c[1] if len(P.c)>1 else F(0)))
    s = f'theorem inner_branch_{i} (x : ℝ) (hl : {rat(l)} < x) (hr : x < {rat(r)}) :\n'
    s += f'    innerR x = {affine(P)} := by\n'
    s += floorproof('ht','2 * (23 / 20) * x',T)
    s += f'  have hi := integral_three_strips (innerGammaIntegrand x) {affine(a)} {affine(b)}\n'
    s += f'      ({values[0]}) ({values[1]}) ({values[2]}) (by linarith) (by linarith) (by linarith)\n'
    # Provide the three hypotheses in a separate fully typed have.
    s = s.replace('  have hi :=', '  have hi : (∫ z in (0 : ℝ)..(1 / 2), innerGammaIntegrand x z) =\n'
        f'      {affine(a)} * ({values[0]}) + ({affine(b)} - {affine(a)}) * ({values[1]}) +\n'
        f'        (1 / 2 - {affine(b)}) * ({values[2]}) := by\n    apply')
    for j,v in enumerate(floors):
        s += '    · intro z hz\n      rcases hz with ⟨hzl, hzr⟩\n'
        for k,expr in enumerate(['x - z','x + z','(3 / 40) * x - z','(3 / 40) * x + z']):
            s += floorproof(f'h{k}',expr,v[k],'      ')
        s += '      simp only [innerGammaIntegrand, innerT, innerB, innerEll, ht, h0, h1, h2, h3]\n      norm_num\n'
    for name,expr,val in [('hq','2 * x',int(2*mid//1)),('hx','x',int(mid//1)),
            ('ha','(3 / 40) * x',int(alpha*mid//1)),('hm','2 * ((37 / 40) * x)',int(2*lam*mid//1))]:
        s += floorproof(name,expr,val)
    s += '  simp only [innerR, innerGamma, hi, innerScalar, innerS, innerNplus,\n'
    s += '    innerT, innerQ, innerJ, ht, hq, hx, ha, hm]\n'
    s += '  norm_num\n  simp only [max_def]\n  split <;> linarith\n\n'
    group=i//10
    path=out/f'Group{group:02}.lean'
    if i%10==0:
        path.write_text('import Zeta5.Certificate.InnerDefinitions\n\n'
          '/-! Generated by `scripts/generate_inner_branches.py`. Each theorem\n'
          'checks its complete domain using proof-producing arithmetic. -/\n\n'
          'namespace Zeta5.Certificate\n\n')
    with path.open('a') as fobj: fobj.write(s)
    if i%10==9 or i==142:
        with path.open('a') as fobj: fobj.write('end Zeta5.Certificate\n')
print(f'Generated {len(rows)} checked-branch proof scripts in {out.relative_to(ROOT)}')

# Tables are transparent real expressions; all lookups and each branch dispatch
# reduce in the kernel. No native evaluator or JSON oracle is used by Lean.
p = ROOT / 'Zeta5' / 'Certificate' / 'InnerPartition.lean'
s = ''.join(f'import Zeta5.Certificate.InnerBranches.Group{g:02}\n' for g in range(15))
s += '\n/-! Generated source partition and branch assembly. -/\n\nnamespace Zeta5.Certificate\n\nopen Set\n\n'
for name, vals in [('innerEndpoint',points),('innerIntercept',[row[2] for row in rows]),
        ('innerSlope',[row[3] for row in rows])]:
    s += f'noncomputable def {name} : ℕ → ℝ\n'
    for i,v in enumerate(vals): s += f'  | {i} => {rat(v)}\n'
    s += '  | _ => 0\n\n'
s += """set_option maxHeartbeats 1000000
set_option maxRecDepth 4096

theorem innerEndpoint_increasing (i : ℕ) (hi : i < 143) :
    innerEndpoint i < innerEndpoint (i + 1) := by
  interval_cases i
"""
for l,r in zip(points, points[1:]):
    s += f'  · change ({rat(l)} : ℝ) < {rat(r)}\n    norm_num\n'
s += """
theorem innerEndpoint_pos (i : ℕ) (hi : i ≤ 143) :
    0 < innerEndpoint i := by
  interval_cases i
"""
for v in points:
    s += f'  · change (0 : ℝ) < {rat(v)}\n    norm_num\n'
s += """
theorem inner_branches (i : ℕ) (hi : i < 143) (x : ℝ)
    (hx : x ∈ Ioo (innerEndpoint i) (innerEndpoint (i + 1))) :
    innerR x = innerIntercept i + innerSlope i * x := by
  interval_cases i
"""
for i in range(143): s += f'  · exact inner_branch_{i} x hx.1 hx.2\n'
s += '\nend Zeta5.Certificate\n'
p.write_text(s)

s = '''import Zeta5.Certificate.InnerPartition

/-! Exact rational integration of the branch data. Each prefix sum is proved
separately so checking does not duplicate a large expanded sum. -/

namespace Zeta5.Certificate

noncomputable def innerPieceValue (i : ℕ) : ℝ :=
  innerSlope i * (1 / innerEndpoint i - 1 / innerEndpoint (i + 1)) +
    innerIntercept i / 2 * (1 / innerEndpoint i ^ 2 - 1 / innerEndpoint (i + 1) ^ 2)

private theorem inner_partial_sum_0 :
    (∑ i ∈ Finset.range 0, innerPieceValue i) = 0 := by simp

'''
total = F(0)
for i,(l,r,b,a) in enumerate(rows):
    value = a*(1/l-1/r)+b/2*(1/l**2-1/r**2)
    prev = total
    total += value
    s += f'''private theorem inner_partial_sum_{i+1} :
    (∑ i ∈ Finset.range {i+1}, innerPieceValue i) = {rat(total)} := by
  rw [Finset.sum_range_succ, inner_partial_sum_{i}]
  change {rat(prev)} + ({rat(a)} * (1 / {rat(l)} - 1 / {rat(r)}) +
    {rat(b)} / 2 * (1 / {rat(l)} ^ 2 - 1 / {rat(r)} ^ 2)) = {rat(total)}
  norm_num

'''
s += f'''theorem inner_exact_sum :
    (∑ i ∈ Finset.range 143, innerPieceValue i) = {rat(total)} :=
  inner_partial_sum_143

end Zeta5.Certificate
'''
(ROOT / 'Zeta5' / 'Certificate' / 'InnerSum.lean').write_text(s)
